# Generated by Django 5.0.4 on 2024-07-02 15:00

from django.db import migrations


multiplier_price = 120


def generate_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        smartphone.price = len(smartphone.brand) * multiplier_price

    smartphone_model.objects.bulk_update(smartphones, ['price'])


def reverse_generated_price(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        smartphone.price = smartphone_model._meta.get_field('price').default

    smartphone_model.objects.bulk_update(smartphones, ['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(
            code=generate_price,
            reverse_code=reverse_generated_price,
        ),
    ]
