# Generated by Django 5.0.4 on 2024-07-02 15:00

from django.db import migrations


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'

    smartphone_model.objects.bulk_update(smartphones, ['category'])


def reverse_set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    smartphones = smartphone_model.objects.all()

    for smartphone in smartphones:
        smartphone.category = smartphone_model._meta.get_field('category').default

    smartphone_model.objects.bulk_update(smartphones, ['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_generate_price'),
    ]

    operations = [
        migrations.RunPython(
            code=set_category,
            reverse_code=reverse_set_category,
        ),
    ]
